name: Build and Publish

on: 
  workflow_call:
    secrets:
      gh_token:
        required: true
    inputs:
      excessiveMode:
        description: 'If true, this will download the ZIP of every releases to calculate the zipSha256 hash, which is unnecessary'
        default: false
        required: false
        type: boolean
      includeDownloadCount:
        description: 'If true, this will append the number of downloads of the package to the package description'
        default: false
        required: false
        type: boolean

env:
  subfolder: subf

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
    - name: Checkout caller repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        ref: ${{ github.ref }}
        
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: hai-vr/pristine-listing-action
        ref: main
        path: ${{ env.subfolder }}
        clean: false

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Build project
      run: dotnet build ${{ env.subfolder }}/pristine-listing-action.csproj

    - name: Run project
      env:
        IN__GITHUB_TOKEN: ${{ secrets.gh_token }}
        IN__EXCESSIVE_MODE: ${{ inputs.excessiveMode }}
        IN__INCLUDE_DOWNLOAD_COUNT: ${{ inputs.includeDownloadCount }}
      run: dotnet run --project ${{ env.subfolder }}/pristine-listing-action.csproj

    ## From https://github.com/actions/upload-pages-artifact (MIT)
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: output/ # Hai: index.json needs to be in there.

  ## From https://github.com/actions/deploy-pages (MIT)
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages ment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
